networks:
  roboshop:
    driver: bridge

services:
  mongodb:
    build : 
      context : ./mongodb
      dockerfile: dockerfile
    image: mongodb:v1
    container_name: mongodb
    networks:
      - roboshop
  
  catalogue:
    build:
      context: ./catalogue
      dockerfile: dockerfile
    image: catalogue:v1
    container_name: catalogue
    networks:
      - roboshop
    depends_on:
      - mongodb
  
  # redis:
  #   image: redis:7
  #   container_name: redis
  #   networks:
  #     - roboshop
  
  # user:
  #   build:
  #     context: ./user
  #     dockerfile: dockerfile
  #   image: user:v1
  #   container_name: user
  #   networks:
  #     - roboshop
  #   depends_on:
  #     - mongodb
  #     - redis
    
    
