FROM node:20
WORKDIR /opt/server
COPY *.js .
COPY *.json .
RUN npm install
EXPOSE 8080
ENV MONGO=true \
    REDIS_URL='redis://redis:6379' \
    MONGO_URL="mongodb://mongodb:27017/users"
CMD ["server.js"]
ENTRYPOINT [ "node" ]
